version: "3.9"
services:

  proxy:
    image: 'nginx:latest'
    container_name: 'proxy'
    restart: unless-stopped
    ports:
      - '8080:8080'
      - '4020:4020'
      - '4030:4030'
      - '4040:4040'
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - bdsnetwork

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8989:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - bdsnetwork

  bdm1:
    container_name: bdm1
    image: mysql:debian
    environment:
      MYSQL_ROOT_PASSWORD: "senha123"
      MYSQL_DATABASE: "aula01"
    networks:
      - bdsnetwork

  bdg1:
    container_name: bdg1
    image: mongo:4.4.6
    volumes:
      - /data/mongodb:/data
    environment:
      MONGO_INITDB_ROOT_PASSWORD: "senha123"
      MONGO_INITDB_ROOT_USERNAME: "mongoadmin"
    networks:
      - bdsnetwork

  mongo-express:
    image: mongo-express:0.54
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: "bdg1"
    ports:
      - "8081:8081"
    networks:
      - bdsnetwork

  bdp1:
    container_name: bdp1
#    restart: unless-stopped
    image: postgres
#    volumes:
#      - ./data/postgres:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: "senha123"
    networks:
      - bdsnetwork

networks:
  bdsnetwork:
    name: bdsnetwork
    driver: bridge

